services:
  accounts:
    image: "danmd96/accounts:v1"
    container_name: "ACCOUNTS_MS"
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybank
  loans:
    image: "danmd96/loans:v1"
    container_name: "LOANS_MS"
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybank
  cards:
    image: "danmd96/cards:v1"
    container_name: "CARDS_MS"
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybank
networks:
  eazybank:
    driver: "bridge"
