server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ""
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: accounts
  # config:
  #   import:
  #   - "application_qa.yaml"
  #   - "application_prod.yaml"
  # profiles:
  #   active:
  #   - default

application:
  version: "0.0.1"

accounts:
  message: "Accounts service is available (default)"
  contactDetails:
    phone: "+1-555-0123"
    email: "support@eazy.com"
  onCallSupport:
    - "team-a"
    - "team-b"
