spring:
  config:
    activate:
      on-profile:
      - prod

application:
  version: "0.0.3"

accounts:
  message: "Accounts service is available in Production"
  contactDetails:
    phone: "+1-555-0123"
    email: "support@eazy.com"
  onCallSupport:
    - "team-a"
    - "team-b"
